default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  # If you using docker the host should be "db"
  host: localhost
  port: 5432

development:
 <<: *default
 database: <%= ENV['DB_NAME'] %>_development

test:
 <<: *default
 database: <%= ENV['DB_NAME'] %>_test

production:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
